[theme]
# Primary theme color (blue) - assuming rgb(154, 252, 255) or similar blue shade
primaryColor = "#4A90E2"

# Background color (white)
backgroundColor = "#ffffff"

# Secondary background color (light gray)  
secondaryBackgroundColor = "#f0f2f6"

# Text color (dark gray)
textColor = "#262730"

# Font family
font = "sans serif"

# Custom CSS colors for pink accent: rgb(222, 0, 185) = #de00b9

[server]
# Port configuration
port = 8501

# Enable CORS for all origins
enableCORS = false

# Enable XSS protection
enableXsrfProtection = true

[browser]
# Automatically open browser when starting
gatherUsageStats = false

[client]
# Show error details in production
showErrorDetails = true
